# Generated by Django 2.1.5 on 2019-08-06 21:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(db_column='building_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(db_column='company_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='companies', related_query_name='company', to='test_app.Building')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(db_column='item_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('identification_number', models.CharField(max_length=15, unique=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', related_query_name='item', to='test_app.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('part', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('id', models.BigAutoField(db_column='item_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('identification_number', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='patent',
            field=models.ManyToManyField(db_table='item_patents', related_name='items', related_query_name='item', to='test_app.Patent'),
        ),
        migrations.AlterUniqueTogether(
            name='ownership',
            unique_together={('content_type', 'user')},
        ),
    ]
